// Users

export const GET_USERS = 'users/GET_USERS';
export const GET_USERS_SUCCESS = 'users/GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'users/GET_USERS_FAILURE';
export const GET_USERS_REFRESH = 'users/GET_USERS_REFRESH';

//  User
export const LOGIN_USER = 'user/LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'user/LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'user/LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'user/LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'user/LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'user/LOGOUT_USER_FAILURE';

export const REMOVE_USER = 'user/REMOVE_USER';
export const REMOVE_USER_SUCCESS = 'user/REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'user/REMOVE_USER_FAILURE';
export const REMOVE_USER_REFRESH = 'user/REMOVE_USER_REFRESH';

export const GET_USER_PROFILE_REQUEST = 'user/GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'user/GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'user/GET_USER_PROFILE_FAILURE';

// Product to be uploaded
export const UPLOAD_PRODUCT = 'product/UPLOAD_PRODUCT';
export const UPLOAD_PRODUCT_SUCCESS = 'product/UPLOAD_PRODUCT_SUCCESS';
export const UPLOAD_PRODUCT_FAILURE = 'product/UPLOAD_PRODUCT_FAILURE';
export const UPLOAD_PRODUCT_REFRESH = 'product/UPLOAD_PRODUCT_REFRESH';

export const UPLOAD_PRODUCT_IMG = 'product/UPLOAD_PRODUCT_IMG';
export const UPLOAD_PRODUCT_IMG_REFRESH = 'product/UPLOAD_PRODUCT_IMG_REFRESH';
export const UPLOAD_PRODUCT_IMG_SUCCESS = 'product/UPLOAD_PRODUCT_IMG_SUCCESS';
export const UPLOAD_PRODUCT_IMG_FAILURE = 'product/UPLOAD_PRODUCT_IMG_FAILURE';

// Product
export const REMOVE_PRODUCT = 'product/REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'product/REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_FAILURE = 'product/REMOVE_PRODUCT_FAILURE';
export const REMOVE_PRODUCT_REFRESH = 'product/REMOVE_PRODUCT_REFRESH';

export const UPDATE_PRODUCT = 'product/UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'product/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'product/UPDATE_PRODUCT_FAILURE';
export const UPDATE_PRODUCT_REFRESH = 'product/UPDATE_PRODUCT_REFRESH';

// Cart
export const ADD_CART_REQUEST = 'cart/ADD_CART_REQUEST';
export const ADD_CART_SUCCESS = 'cart/ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'cart/ADD_CART_FAILURE';

export const GET_CART_REQUEST = 'cart/GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'cart/GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'cart/GET_CART_FAILURE';

export const REFRESH_CART_REQUEST = 'cart/REFRESH_CART_REQUEST';
export const REFRESH_CART_SUCCESS = 'cart/REFRESH_CART_SUCCESS';
export const REFRESH_CART_FAILURE = 'cart/REFRESH_CART_FAILURE';

export const CHANGE_ITEM_QUANTITY = 'cart/CHANGE_ITEM_QUANTITY';

export const DELETE_ITEM_REQUEST = 'cart/DELETE_ITEM_REQUEST';
export const DELETE_ITEM_SUCCESS = 'cart/DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'cart/DELETE_ITEM_FAILURE';

// Checkout

export const ADD_TO_CHECKOUT = 'checkout/ADD_TO_CHECKOUT';
export const REFRESH_CHECKOUT = 'checkout/REFRESH_CHECKOUT';

// Order

export const ADD_ORDER_REQUEST = 'order/ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'order/ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILURE = 'order/ADD_ORDER_FAILURE';

export const GET_ORDERS_REQUEST = 'admin_orders/GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'admin_orders/GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'admin_orders/GET_ORDERS_FAILURE';
